name: Build

on:
    push:
    pull_request:

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'

            - name: Set up Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                  validate-wrappers: true

            - name: Build and test
              run: ./gradlew build
