name: Release

on:
    workflow_dispatch:
        inputs:
            repository:
                description: 'Select the repository to publish to'
                required: true
                type: choice
                options:
                    - Releases
                    - Snapshots

permissions:
    contents: read

jobs:
    publish:
        runs-on: macos-latest
        environment: Release

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'

            - name: Set up Gradle caching
              uses: gradle/actions/setup-gradle@v3
              with:
                  validate-wrappers: true

            - name: Run publish task
              env:
                  KIT_MAVEN_USERNAME: ${{ secrets.DEFTU_PUBLISHING_USERNAME }}
                  KIT_MAVEN_PASSWORD: ${{ secrets.DEFTU_PUBLISHING_PASSWORD }}
              run: ./gradlew publishAllPublicationsToDeftu${{ github.event.inputs.repository }}Repository
